"""Full new beginnnig

Revision ID: 3dd3c4a05072
Revises: 
Create Date: 2021-07-20 10:47:53.437841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd3c4a05072'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instituicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disciplina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=True),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criada', sa.DateTime(), nullable=False),
    sa.Column('semestre_letivo', sa.String(length=5), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('inicio', sa.Integer(), nullable=False),
    sa.Column('fim', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etapa', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=True),
    sa.Column('aulas_num', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicao.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_turma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Enum('DOM', 'SEG', 'TER', 'QUA', 'QUI', 'SEX', 'SAB', name='dias'), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turma_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Enum('DOM', 'SEG', 'TER', 'QUA', 'QUI', 'SEX', 'SAB', name='dias'), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('config', sa.Enum('INDISPONIVEL', 'PRE_AGENDADA', name='config'), nullable=False),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turma_config')
    op.drop_table('grade_turma')
    op.drop_table('turma')
    op.drop_table('professor')
    op.drop_table('periodo')
    op.drop_table('grade')
    op.drop_table('disciplina')
    op.drop_table('instituicao')
    # ### end Alembic commands ###
