"""Solver fixing

Revision ID: 7fcd18cfee8f
Revises: 4ec6418390da
Create Date: 2021-07-13 00:03:43.718792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcd18cfee8f'
down_revision = '4ec6418390da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplina', sa.Column('codigo', sa.String(length=10), nullable=True))
    op.add_column('grade_turma', sa.Column('dia', sa.Integer(), nullable=False))
    op.add_column('periodo', sa.Column('nome', sa.String(length=50), nullable=True))
    op.drop_column('periodo', 'dia')
    op.add_column('turma', sa.Column('etapa', sa.Integer(), nullable=False))
    op.add_column('turma', sa.Column('codigo', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turma', 'codigo')
    op.drop_column('turma', 'etapa')
    op.add_column('periodo', sa.Column('dia', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('periodo', 'nome')
    op.drop_column('grade_turma', 'dia')
    op.drop_column('disciplina', 'codigo')
    # ### end Alembic commands ###
